version: "3.5"

services:
  resty:
    image: resty
    container_name: resty
    build:
      context: ./
    volumes:
      - ${PWD}/lua:/usr/local/openresty/nginx/lua
      - ${PWD}/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ${PWD}/sites.d/default.conf:/usr/local/openresty/nginx/conf/sites.d/default.conf
    network_mode: host
    privileged: true
